config/routes.rb
Rails.application.routes.draw do
 
	devise_for :users
	resources :posts do
		resources :comments
	end

 root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :user
has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base

  include Gravtastic
  gravtastic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  has_many :comments
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))	
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment=@post.comments.find(params[:id])

	end

	def update
		@post = Post.find(params[:post_id])
		@comment=@post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment=@post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :find_post, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]


def index
@posts = Post.all.order("created_at DESC").page(params[:page]).per(5)
end

def show

end

def new
@post = current_user.posts.build
end

def create
@post = current_user.posts.build(post_params)

if @post.save 
	redirect_to @post
else
	render 'new'
end

end

def edit
end

def update
	if @post.update(post_params)
		redirect_to @post
	else
		render 'edit'
	end
end

def destroy
	@post.destroy
	redirect_to root_path
end


private

def find_post
	@post= Post.find(params[:id])
end


def post_params
	params.require(:post).permit(:title, :content)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">

	<div class="content">
		<div class="gravatar"><%= image_tag comment.user.gravatar_url%></div>
		<p class="comment_author"><%= comment.user.email %></p>
		<p class="comment_date"> <%=time_ago_in_words(comment.created_at)%></p>
		<p class="comment_content"> <%= comment.comment %></p>

	</div>

	<div class="buttons">
		<%= link_to "Editar", edit_post_comment_path(comment.post, comment) %>
		<%= link_to "Eliminar", [comment.post, comment], method: :delete, data: { confirm: "Estas seguro de eliminar esto?" } %>	
	</div>

</div>	

app/views/comments/_form.html.erb
<%=simple_form_for([@post, @post.comments.build]) do |f|%>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edición</h1>

<%= simple_form_for([@post, @comment]) do |f| %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foro</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
	<link href="	https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css" rel="stylesheet" type='text/css'>
  
</head>
<body>
<header class="main_header clearfix">

<div class="wrapper">
	<div id="logo">
		<p><%= link_to "Foro de Consultas", root_path %></p>
	</div>
	<%if user_signed_in?%> 
		<div id="button">
			<%= link_to "Nueva Publicación", new_post_path(@post) %>
		</div>	
	<%else%>
	<div id="button">
		<%= link_to "Registrese", new_user_registration_path %>
		<%= link_to "Iniciar", new_user_session_path %>
	</div>	
	<%end%>
</div>
	
</header>



<div class="wrapper">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>	
</div>

<div class="wrapper">
	<%= yield %>	
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <br>
  <%= f.input :content %>
  <br>
  <%= f.button :submit %>
  <%= link_to "Cancelar", :back %>

<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Editar publicación</h1>

	<%= render 'form' %>
	<br>

</div>

app/views/posts/index.html.erb
<h1>Listado de Posts</h1>

<%= paginate @posts%>

<br><br><br>

<div id="posts">
	<% @posts.each do |post| %>
	<div class="post">
		<h2 class="title"><%= link_to post.title, post%></h2>
		<p class="date">Publicado el <%= post.created_at.strftime("%d, %B, %Y") %> por <%= post.user.email %></p>
		<%if post.comments.count == 1%>
		<p class="key_comments"><%= post.comments.count %> Comentario </p>
		<%else%>
		<p class="key_comments"><%= post.comments.count %> Comentarios </p>
		<%end%>
	</div>
	<% end %>	
</div>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>Nueva publicación</h1>
	<%= render 'form'%>	
</div>

app/views/posts/show.html.erb
<div id="post_content">

	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Creado hace <%=time_ago_in_words(@post.created_at)%>
	</p>

	<p class="body">
		<%= @post.content %>
	</p>

	<div id="comments">

		<h2><%= @post.comments.count%> Comentarios <br><br> <%=render @post.comments%></h2>

		<h3>Responder al tema <br><br> <%=render 'comments/form'%> </h3>
		
		<br>
		<hr>

		<div class="button">
			<%= link_to "Editar", edit_post_path(@post)%>
			<%= link_to "Borrar", post_path(@post), method: :delete, data: {confirm: "Estas seguro de eliminar esto?"} %>
			<%= link_to "Inicio", root_path %>

		</div>
		<br><br>

	</div>
	
</div>